use_frameworks!

platform :ios, '9.0'

target 'LYZEasyNavigation_Example' do
  pod 'LYZEasyNavigation', :path => '../'

  target 'LYZEasyNavigation_Tests' do
    inherit! :search_paths

    
  end
end
